package:
    name: r-ggbiplot
    version: '0.55'
source: 
    url:https://github.com/vqv/ggbiplot/archive/master.zip
build:
    umber: 1
    rpaths:
     	- lib/R/lib/
    	- lib/
requirements:
    build: 
	- {{ compiler('c') }}
    host:
	- r-base
        - r-devtools
        - r-ggplot2
        - r-plyr
        - r-scales
        - r-gridbase
    run:
        - r-base
        - r-devtools
        - r-ggplot2
        - r-plyr
        - r-scales
        - r-gridbase
test:
    commands:
        - 'R -e "library(ggbioplot)"'
about:
    date: '2011-10-23'
    summary:  "A biplot based on ggplot2"
    home: http://github.com/vqv/ggbiplot
    license: GPL-2
