# This file created by conda-build 2.1.2
# meta.yaml template originally from:
# /sandbox/ylelievre/packages/r-ggbiplot, last modified Mon Mar  6 13:15:48 2017
# ------------------------------------------------

package:
    name: r-ggbiplot
    version: '0.55'
source: {}
build:
    string: py35r3.3.1_0
requirements:
    build: []
    run:
        - python
        - setuptools
        - r-base
        - r-devtools
        - r-ggplot2
        - r-plyr
        - r-scales
        - r-gridbase
test:
    commands:
        - 'R -e "library(ggbioplot)"'
about:
    date: '2011-10-23'
    home: http://github.com/vqv/ggbiplot
    license: GPL-2
