package:
    name: r-ggbiplot
    version: '0.55'
source: {}
build:
    string: py35r3.3.1_0
requirements:
    build: []
    run:
        - python
        - setuptools
        - r-base
        - r-devtools
        - r-ggplot2
        - r-plyr
        - r-scales
        - r-gridbase
test:
    commands:
        - 'R -e "library(ggbioplot)"'
about:
    date: '2011-10-23'
    summary:  "ggbiplot"
    home: http://github.com/vqv/ggbiplot
    license: GPL-2
