{% set version="0.1.0" %}
{% set name="LncPipeReporter" %}
{% set sha256sum="30f19ea1b5148bc1d53c863c86a011632cdf143250f513ab6f43e45601abe88c" %}

package:
  name: 'r-{{ name|lower }}'
  version: '{{ version }}'
source:
  url: https://github.com/bioinformatist/LncPipeReporter/archive/v{{ version }}tar.gz
  sha256:  {{ sha256sum }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - r-base
    - libgfortran-ng  # work around bug in r-base with Rcpp
  run:
    - r-base
    - libgfortran-ng  # work around bug in r-base with Rcpp
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: https://github.com/bioinformatist/LncPipeReporter
  license: The MIT License (MIT)
  summary:  An R package for automatically aggregating and summarizing lncRNA analysis results.
